spring.application.name=whatsapp-sales-agent

# Configuration for Ollama (AI Agent)
# Chat / response generation
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3

# Embeddings / semantic search
spring.ai.ollama.embedding.options.model=nomic-embed-text

# ===============================
# MySQL Database
# ===============================

#spring.datasource.url=jdbc:mysql://localhost:3306/whatsapp_sales_agen
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# WhatsApp
whatsapp.verify-token=${WHATSAPP_VERIFY_TOKEN}

# WhatsApp Cloud API
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN}
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID}